services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=my_project
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123